## paperspace
## tmux - multiple screens
## tensor = array

In [ ]:
## nomenclature
# error/loss = target - calculated

In [2]:
# non linear - activation functions

# Slide 24, Slide 25 of neuralNetwork.pptx

In [49]:
import numpy as np

In [50]:
#Slide 25
weights_1 = np.array([[0.71,0.112],[0.355,0.856],[0.268,0.468]])
x = np.array([1,1])
print(weights)
print(x)

[[0.71  0.112]
 [0.355 0.856]
 [0.268 0.468]]
[1 1]


In [51]:
y_linear_1 = np.dot(weights,x)
print(y_linear_1)

[0.822 1.211 0.736]


In [52]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))
fn_sigmoid = np.vectorize(sigmoid)

In [53]:
y_nonlinear_1 = fn_sigmoid(y_linear_1)
print(y_nonlinear_1)

[0.69466072 0.77047584 0.67612055]


In [54]:
weights2 = np.array([0.116,0.329,0.708]) # 1x3

In [55]:
y_linear_2 = np.dot(weights2,y_nonlinear_1)
print(y_linear_2)

0.8127605425998854


In [56]:
y_nonlinear_2 = fn_sigmoid(y_linear_2)
print(y_nonlinear_2)

0.6926974470214398


# Slide 26

In [64]:
import math

weights_list = []
weights_list.append(np.array([[0.71,0.112],[0.355,0.856],[0.268,0.468]]))
weights_list.append(np.array([0.116,0.329,0.708]))
input_x = np.array([1,1])

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

fn_sigmoid = np.vectorize(sigmoid)

def calc(weight,x):
    y_linear = np.dot(weight,x)
    y_nonlinear = fn_sigmoid(y_linear)
    return y_nonlinear

for weight in weights_list:
    y = calc(weight,input_x)
    input_x = y

print (y)

0.6926974470214398
