<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.


It provides n-dimensional array of the same data-type and built-n functions which are fast and space-efficient.

Elementary introduction of numpy for beginners so that they can have the hang of it.
The key topics will be covering are:

    Creation of ndarray
	Indexing & Slicing 
	Arithmetic Array Operations 
	Statistical Methods
	Set Operations
	Broadcasting

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



# Sample Data that we will be Dealing with

https://www.kaggle.com/c/digit-recognizer/data - Image Processing

https://www.kaggle.com/c/imaterialist-challenge-fashion-2018 - Image Identification

https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data - Data Prediction

https://www.kaggle.com/c/movie-review-sentiment-analysis-kernels-only - Natural Language Processing

# Why Numpy

In [10]:
import numpy as np;

#Numpy Array
my_arr = np.arange(1000000)

#Python Array
my_list = list(range(1000000))

print (len(my_arr))
print (len(my_list))

1000000
1000000


In [13]:
#Now let’s multiply each sequence by 2
# Numpy is extremely fast compared to usual collections (traditional list in this case)

%time for _ in range(50): my_arr2 = my_arr * 2 #Numpy processing time

%time for _ in range(50): my_list2 = [x * 2 for x in my_list] #loop based processing

CPU times: user 52.4 ms, sys: 4.34 ms, total: 56.7 ms
Wall time: 54.5 ms
CPU times: user 2.43 s, sys: 214 ms, total: 2.64 s
Wall time: 2.64 s


# NumPy data types

In [4]:
vector = np.array([1, 2, 3])
print(vector)

[1 2 3]


In [5]:
matrix = np.array([[1,2,3],
              [4,5,6]])
print (matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
tensor = np.array([
                [[1,2,3], 
               [4,5,6]],
                   
              [[21,22,33],
               [44,55,66]]
            ])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[21 22 33]
  [44 55 66]]]


In [7]:
print(vector.shape)
print(matrix.shape)
print(tensor.shape)

(3L,)
(2L, 3L)
(2L, 2L, 3L)


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Let's get started by creating ndarrays using the numpy package.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create Rank 1 numpy arrays:
</p>

In [8]:
import numpy as np                 #import numpy package into notebook

an_array = np.array([3, 33, 333],dtype=np.int32)  # Create a rank 1 array

print(an_array)
print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"
print(an_array.dtype)
print(an_array.shape)              # Attribute, provide the dimensionality if array, in case 1D-> length of array
print(an_array.size)

[  3  33 333]
<type 'numpy.ndarray'>
int32
(3L,)
3


In [ ]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

In [ ]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to access a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [ ]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print(another.shape)  # rows x columns 

#print(another.size) 

#print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [ ]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2)) 
#ex1 = np.zeros((2,2),int)      
print(ex1)                              

In [ ]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

In [ ]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

In [14]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [ ]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((5,5))
print(ex5)    

In [2]:
x = np.arange(1,10).reshape(3,3) 
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing & Slicing

<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

We can use slice indexing to pull out sub-regions of ndarrays.
It will be used to divide a dataset into training, cross-validation, testing set.

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)


In [ ]:
print('1st element:', x[0])      #positve indices from begining of the array
print('2nd element:', x[1])
#print('5th element:', x[4])

When you modify a slice, you actually modify the underlying array.

In [ ]:
print('1st element:', x[-5])    #negative indices from end of the array
print('2nd element:', x[-4])
#print('5th element:', x[-1])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

We can use slice indexing to pull out sub-regions of ndarrays.
1. ndarray[start : end]     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Started is included & end is excluded
2. ndarray[start : ]        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       From starting index to end
3. ndarray[ : end]

In [16]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# [1,2,3,4],[5,6,7,8]

print(a[:2])
#print(a[:,0])

[[1 2 3 4]
 [5 6 7 8]]
[1 5 9]


In [27]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] #Multiple slices 

print (b)

[[2 3]
 [6 7]]


Excercise

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) #3x3 matrix

# Retireve rows(0,1) , column (1rst onward)

# Retireve Last row all columns

# Retirive [5,6],[8,9]



When you modify a slice, you actually modify the underlying array.

In [ ]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a_slice = an_array[:2, 1:3]
print(a_slice)

print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])  


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [ ]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

In [4]:
# you can use this to force floats into integers 
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [5]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [ ]:
import numpy as np

x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

In [ ]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"


In [ ]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

In [ ]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

In [ ]:
# divide
print(x / y)
print()
print(np.divide(x, y))

In [ ]:
# square root
print(np.sqrt(x))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [18]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ 11.29890812  14.11320051  -4.01755394   4.13859493  -4.91847673]
 [-11.59276473  -9.5261459   -9.10668046   6.76096985  13.6631894 ]]


In [ ]:
# compute the mean for all elements
print(arr.mean())

In [9]:
# compute the means by row
print(arr.mean(axis = 1))

[-1.39445709  2.12755878]


In [10]:
# compute the means by column
print(arr.mean(axis = 0))

[ 0.58440125 12.6054958  -2.7209532  -5.93223431 -2.70395533]


In [19]:
# sum all the elements
print(arr.sum())
# sum all the elements across columns

10.81324106516678


In [11]:
# compute the medians, across rows
print(np.median(arr, axis = 1))

[ 2.9197295  -4.55540517]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [20]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 0.22740897  3.37374     1.37455619 -0.96942288  0.00342456 -0.85111793
  1.6558371  -1.2055064  -1.16941154 -0.90245113]


In [21]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.2055064  -1.16941154 -0.96942288 -0.90245113 -0.85111793  0.00342456
  0.22740897  1.37455619  1.6558371   3.37374   ]

[ 0.22740897  3.37374     1.37455619 -0.96942288  0.00342456 -0.85111793
  1.6558371  -1.2055064  -1.16941154 -0.90245113]


In [22]:
# inplace sorting
unsorted.sort() 

print(unsorted)

[-1.2055064  -1.16941154 -0.96942288 -0.90245113 -0.85111793  0.00342456
  0.22740897  1.37455619  1.6558371   3.37374   ]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])
#array.shape
print(np.unique(array))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

In [ ]:
print( np.intersect1d(s1, s2) ) 

In [ ]:
print( np.union1d(s1, s2) )

In [ ]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic.

A way to overcome this is to duplicate the smaller array so that it is the dimensionality and size as the larger array. This is called array broadcasting and is available in NumPy when performing array arithmetic, which can greatly reduce and simplify your code.



Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [24]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [31]:
import numpy as np
start = np.zeros((4,3))
print(start)
print()
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1 0 2]


In [32]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [33]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [34]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [35]:
# this will just broadcast in both dimensions
start = np.zeros((2,2))
add_scalar = np.array([1])  
print(start)
print(add_scalar)
print(start+add_scalar)

[[0. 0.]
 [0. 0.]]
[1]
[[1. 1.]
 [1. 1.]]


In [ ]:
#•The last dimension of each array is compared. 
    #•If the dimension lengths are equal, or one of the dimensions is of length 1, then we keep going.
    #•If the dimension lengths aren't equal, and none of the dimensions have length 1, then there's an error.

import numpy as np
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A.shape)
#b=np.array([[1, 2], [1, 2]])#2*2
#b = np.array([1, 2])#1*2
#b = np.array([1, 2, 1])#1*3
#b= np.array([1])
#b = np.array([[1],[2]])#2*1
print(b.shape)
C = A + b
print(C)


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

In [ ]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
np.save('an_array', x)

In [ ]:
np.load('an_array.npy')

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p>

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

In [ ]:
!cat array.txt

In [ ]:
np.loadtxt('array.txt', delimiter=',')

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Metrices 

</p>

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [ ]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T