In [1]:
import numpy as np;

In [18]:
# Print the numpy version and the configuration
print(np.version.version)
print(np.__version__)
print(np.show_config())

1.14.3
1.14.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
None


In [24]:
# Create a vector with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
# Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(0,9)
y = x.reshape(3,3)
print (y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
# Reverse a vector (first element becomes last)
x = np.arange(0, 10)
y = np.flip(x, axis=0) #requires axis
z = np.flipud(x) #same you can use .fliplr() left-right
print (x)
print (y)
print (z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


In [47]:
# Create a 10x10 array with random values and find the minimum and maximum values
x = 10 * np.random.random((10,10)) # creates 10 x 10 matrix with values between 0 and 1
print (x)
arr = np.random.randn(10,10)
print(arr)
print (arr.max(),arr.min())
z = np.random.randint(1,5,10) # just returns integers with low, high and size
print (z)

[[2.88473667 9.39642715 1.60958667 6.41263243 0.97202938 6.57528404
  9.26650336 4.04908799 4.69589245 1.18147397]
 [8.4710131  0.2062708  8.63085846 9.98997288 6.47292825 1.59885474
  7.94929764 0.26496962 4.56498802 4.25497541]
 [7.53008212 1.78967584 4.90550085 3.46828536 0.24619802 5.97729016
  2.21582357 9.922954   4.11456829 6.18794032]
 [4.49004897 8.15032006 9.81427073 1.439767   5.534838   9.51398724
  1.45436464 0.96277098 3.15053631 6.44021899]
 [9.63728431 5.66062813 1.23801601 0.97783476 0.09249144 9.34250922
  5.2997944  9.35229331 4.09150524 3.048213  ]
 [1.09079541 4.35866221 7.91263629 7.08466382 8.69498572 4.13463119
  7.65497928 7.20698232 7.50245241 7.33520272]
 [1.98506293 4.62717549 1.97377408 7.14988601 1.88034635 2.28262152
  3.09098709 2.82114239 2.73819563 3.26418837]
 [9.61687595 7.36533571 9.59269159 7.73692853 2.83336846 5.8295906
  3.14447363 3.18326433 0.55447604 4.57637338]
 [0.86747011 8.52116441 6.34010788 5.4303464  9.61577676 3.75359442
  5.78344397 

In [66]:
# Create random vector of size 10 and replace the maximum value by 0

vector = np.random.randn(10)
print (vector)
print ("max value at location:" + str(np.nanargmax(vector,0))) #nanargmax
print ('min value at location:' + str(np.argmin(vector,0))) #nanargmin

[-1.07122158 -1.35358607  0.93289995  0.6771103   0.41034194  0.33097167
 -1.50656869  0.19452751 -0.4840283   0.81599577]
max value at location:2
min value at location:6


In [71]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
# https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html
x = np.random.rand(10)
print (x)

[0.58658815 0.44099478 0.20002273 0.77507662 0.83681503 0.74525774
 0.68647037 0.45372951 0.84177576 0.5009998 ]


In [87]:
# Create a random vector of size 30 and find the mean value
x = np.random.rand(30)
print (x)
%time print (np.mean(x))
%time print (x.mean())

[0.77875342 0.46124881 0.65343119 0.40425923 0.21417087 0.05892269
 0.47380473 0.42235508 0.94219568 0.73576651 0.37630402 0.68754127
 0.6124605  0.55363192 0.64964361 0.67373387 0.3557765  0.44781631
 0.16184145 0.72702786 0.24528957 0.44702114 0.48163762 0.83103715
 0.24655585 0.49404077 0.2339575  0.05626445 0.50277181 0.12747848]
0.468557995170898
CPU times: user 74 µs, sys: 6 µs, total: 80 µs
Wall time: 84.9 µs
0.468557995170898
CPU times: user 72 µs, sys: 13 µs, total: 85 µs
Wall time: 87.7 µs


In [82]:
# Create a random vector of size 10 and sort it
x=np.random.rand(10)
y=np.sort(x)
print (x)
print (y)


[0.07741872 0.88661681 0.76422565 0.84308637 0.9515836  0.41946376
 0.31043657 0.51665344 0.05644125 0.55049339]
[0.05644125 0.07741872 0.31043657 0.41946376 0.51665344 0.55049339
 0.76422565 0.84308637 0.88661681 0.9515836 ]


In [103]:
# How to sum a small array faster than np.sum? 
Z = np.arange(100)
%time print(np.sum(Z)) #slower in small arrays
%time print(sum(Z)) #slower in large arrays

4950
CPU times: user 201 µs, sys: 95 µs, total: 296 µs
Wall time: 245 µs
4950
CPU times: user 56 µs, sys: 5 µs, total: 61 µs
Wall time: 66 µs


In [108]:
# Consider two random array A anb B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

%time print (A==B)
%time print (np.array_equal(A,B))

[False False  True  True  True]
CPU times: user 559 µs, sys: 781 µs, total: 1.34 ms
Wall time: 1.22 ms
False
CPU times: user 81 µs, sys: 47 µs, total: 128 µs
Wall time: 133 µs


In [122]:
# How to I sort an array by the nth column?
# https://stackoverflow.com/questions/2828059/sorting-arrays-in-numpy-by-column
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[5 5 3]
 [7 1 2]
 [0 3 1]]
[[0 3 1]
 [5 5 3]
 [7 1 2]]


In [152]:
# How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10))
print(Z)
print (Z.shape)
print (Z[0][1])
print(np.isnan(Z).any())
Z[0][1] = np.nan
print(np.isnan(Z).any())

[[1 2 0 0 2 2 1 1 0 0]
 [0 1 1 2 1 2 2 2 2 2]
 [1 2 2 0 2 0 1 0 1 2]]
(3, 10)
2
False


ValueError: cannot convert float NaN to integer

In [ ]:
# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

A = np.ones((5,5,3))
B = 2*np.ones((5,5))

In [ ]:
# Swap two rows of an array? 

A = np.arange(25).reshape(5,5)


# Special Data types

In addition to dtype objects, NumPy introduces special numeric values: nan (not a number) and inf(infinity)

In [ ]:
What is the result of the following expression? 

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1